default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workers_development

test:
  <<: *default
  database: workers_test

production:
  <<: *default
  database: workers_production
  username: workers
  password: <%= ENV['WORKERS_DATABASE_PASSWORD'] %>
